##################################################################################################
##################################################################################################

include $(ROOTDIR)/make.include

TYPE := bin
TARGETNAME := shell_cli.bin


CCXXFLAGS = -DDEBUG -g
OFLAGS = -L $(TARGET_PATH_R) -lipc -llog  -lfile -ldir -lshm -lmd5 -ldev_rw -lpthread -lrt

#INCLUDES =
#CCXXFLAGS =
#CFLAGS =
#CXXFLAGS =
#OFLAGS =
#EXOBJS =
#EXCLUDESRCS =


include $(ROOTDIR)/make.share
