##################################################################################################
##################################################################################################

include $(ROOTDIR)/make.include

TYPE := staticlib
TARGETNAME := prvtprot

#INCLUDES += -I../asn
CCXXFLAGS = -Wall
#CFLAGS =
#CXXFLAGS =
#OFLAGS =
#EXOBJS =
#EXCLUDESRCS =

include $(ROOTDIR)/make.share
