##################################################################################################
##################################################################################################

include $(ROOTDIR)/make.include

TYPE := staticlib
TARGETNAME := uds

OFLAGS = -L $(TARGET_PATH_R) -luds_server -lJ1939

#INCLUDES =
#CCXXFLAGS =
#CFLAGS =
#CXXFLAGS =
#OFLAGS =
#EXOBJS =
#EXCLUDESRCS =

include $(ROOTDIR)/make.share
