##################################################################################################
##################################################################################################

include $(ROOTDIR)/make.include

TYPE := bin
TARGETNAME := appl.bin


CCXXFLAGS = -DDEBUG -g
OFLAGS = -L $(TARGET_PATH_R) -ldir -lfile -lshm -llog -lmd5 -ldev_rw -lpthread -lrt

#INCLUDES =
#CCXXFLAGS =
#CFLAGS =
#CXXFLAGS =
#OFLAGS =
#EXOBJS =
#EXCLUDESRCS =


include $(ROOTDIR)/make.share
