/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HOZON"
 * 	found in "HOZON_PRIV_v1.0.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_CfgCheckReqInfo_H_
#define	_CfgCheckReqInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <IA5String.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CfgCheckReqInfo */
typedef struct CfgCheckReqInfo {
	OCTET_STRING_t	 mcuSw;
	OCTET_STRING_t	 mpuSw;
	IA5String_t	 vehicleVIN;
	IA5String_t	 iccID;
	IA5String_t	 btMacAddr;
	OCTET_STRING_t	 configSw;
	OCTET_STRING_t	 cfgVersion;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CfgCheckReqInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CfgCheckReqInfo;

#ifdef __cplusplus
}
#endif

#endif	/* _CfgCheckReqInfo_H_ */
#include <asn_internal.h>
