/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HOZON"
 * 	found in "HOZON_PRIV_v1.0.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_CfgReadRespInfo_H_
#define	_CfgReadRespInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <OCTET_STRING.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct FICMConfigSet;
struct APN1ConfigSet;
struct APN2ConfigSet;
struct CommonConfigSet;
struct ExtendConfigSet;

/* CfgReadRespInfo */
typedef struct CfgReadRespInfo {
	BOOLEAN_t	 result;
	OCTET_STRING_t	 cfgVersion;
	struct ficmConfig {
		A_SEQUENCE_OF(struct FICMConfigSet) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ficmConfig;
	struct apn1Config {
		A_SEQUENCE_OF(struct APN1ConfigSet) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *apn1Config;
	struct apn2Config {
		A_SEQUENCE_OF(struct APN2ConfigSet) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *apn2Config;
	struct commonConfig {
		A_SEQUENCE_OF(struct CommonConfigSet) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *commonConfig;
	struct extendConfig {
		A_SEQUENCE_OF(struct ExtendConfigSet) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *extendConfig;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CfgReadRespInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CfgReadRespInfo;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "FICMConfigSet.h"
#include "APN1ConfigSet.h"
#include "APN2ConfigSet.h"
#include "CommonConfigSet.h"
#include "ExtendConfigSet.h"

#endif	/* _CfgReadRespInfo_H_ */
#include <asn_internal.h>
