/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HOZON"
 * 	found in "HOZON_PRIV_v1.0.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_DiagCode_H_
#define	_DiagCode_H_


#include <asn_application.h>

/* Including external dependencies */
#include <IA5String.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DiagCode */
typedef struct DiagCode {
	IA5String_t	 diagCode;
	long	 faultCodeType;
	long	 lowByte;
	long	 diagTime;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DiagCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DiagCode;

#ifdef __cplusplus
}
#endif

#endif	/* _DiagCode_H_ */
#include <asn_internal.h>
