/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HOZON"
 * 	found in "HOZON_PRIV_v1.0.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_DiagnosticStInfo_H_
#define	_DiagnosticStInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct DiagnosticRespInfo;

/* DiagnosticStInfo */
typedef struct DiagnosticStInfo {
	struct diagStatus {
		A_SEQUENCE_OF(struct DiagnosticRespInfo) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} diagStatus;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DiagnosticStInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DiagnosticStInfo;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "DiagnosticRespInfo.h"

#endif	/* _DiagnosticStInfo_H_ */
#include <asn_internal.h>
