/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HOZON"
 * 	found in "HOZON_PRIV_v1.0.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_FICMConfigSettings_H_
#define	_FICMConfigSettings_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* FICMConfigSettings */
typedef struct FICMConfigSettings {
	OCTET_STRING_t	 token;
	OCTET_STRING_t	 userID;
	BOOLEAN_t	 directConnEnable;
	OCTET_STRING_t	 address;
	OCTET_STRING_t	 port;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FICMConfigSettings_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FICMConfigSettings;

#ifdef __cplusplus
}
#endif

#endif	/* _FICMConfigSettings_H_ */
#include <asn_internal.h>
