/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HOZON"
 * 	found in "HOZON_PRIV_v1.0.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_RmtCtrlStRespInfo_H_
#define	_RmtCtrlStRespInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RmtRvsposInfo;
struct RvsBasicStatus;

/* RmtCtrlStRespInfo */
typedef struct RmtCtrlStRespInfo {
	long	 rvcReqType;
	long	 rvcReqStatus;
	long	*rvcFailureType	/* OPTIONAL */;
	struct gpsPosition {
		A_SEQUENCE_OF(struct RmtRvsposInfo) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} gpsPosition;
	struct basicVehicleStatus {
		A_SEQUENCE_OF(struct RvsBasicStatus) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} basicVehicleStatus;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RmtCtrlStRespInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RmtCtrlStRespInfo;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RmtRvsposInfo.h"
#include "RvsBasicStatus.h"

#endif	/* _RmtCtrlStRespInfo_H_ */
#include <asn_internal.h>
