/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HOZON"
 * 	found in "HOZON_PRIV_v1.0.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_RvsBasicStatus_H_
#define	_RvsBasicStatus_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RvsBasicStatus */
typedef struct RvsBasicStatus {
	BOOLEAN_t	*driverDoor	/* OPTIONAL */;
	BOOLEAN_t	 driverLock;
	BOOLEAN_t	*passengerDoor	/* OPTIONAL */;
	BOOLEAN_t	 passengerLock;
	BOOLEAN_t	*rearLeftDoor	/* OPTIONAL */;
	BOOLEAN_t	 rearLeftLock;
	BOOLEAN_t	*rearRightDoor	/* OPTIONAL */;
	BOOLEAN_t	 rearRightLock;
	BOOLEAN_t	*bootStatus	/* OPTIONAL */;
	BOOLEAN_t	 bootStatusLock;
	BOOLEAN_t	*driverWindow	/* OPTIONAL */;
	BOOLEAN_t	*passengerWindow	/* OPTIONAL */;
	BOOLEAN_t	*rearLeftWindow	/* OPTIONAL */;
	BOOLEAN_t	*rearRightWinow	/* OPTIONAL */;
	long	*sunroofStatus	/* OPTIONAL */;
	BOOLEAN_t	 engineStatus;
	BOOLEAN_t	 accStatus;
	long	*accTemp	/* OPTIONAL */;
	long	*accMode	/* OPTIONAL */;
	long	*accBlowVolume	/* OPTIONAL */;
	long	 innerTemp;
	long	 outTemp;
	BOOLEAN_t	 sideLightStatus;
	BOOLEAN_t	 dippedBeamStatus;
	BOOLEAN_t	 mainBeamStatus;
	BOOLEAN_t	 hazardLightStus;
	long	*frtRightTyrePre	/* OPTIONAL */;
	long	*frtRightTyreTemp	/* OPTIONAL */;
	long	*frontLeftTyrePre	/* OPTIONAL */;
	long	*frontLeftTyreTemp	/* OPTIONAL */;
	long	*rearRightTyrePre	/* OPTIONAL */;
	long	*rearRightTyreTemp	/* OPTIONAL */;
	long	*rearLeftTyrePre	/* OPTIONAL */;
	long	*rearLeftTyreTemp	/* OPTIONAL */;
	long	 batterySOCExact;
	long	*chargeRemainTim	/* OPTIONAL */;
	long	 availableOdomtr;
	long	*engineRunningTime	/* OPTIONAL */;
	BOOLEAN_t	 bookingChargeSt;
	long	*bookingChargeHour	/* OPTIONAL */;
	long	*bookingChargeMin	/* OPTIONAL */;
	long	*chargeMode	/* OPTIONAL */;
	long	*chargeStatus	/* OPTIONAL */;
	long	*powerMode	/* OPTIONAL */;
	long	 speed;
	long	 totalOdometer;
	long	 batteryVoltage;
	long	 batteryCurrent;
	long	 batterySOCPrc;
	BOOLEAN_t	 dcStatus;
	long	 gearPosition;
	long	 insulationRstance;
	long	 acceleratePedalprc;
	long	 deceleratePedalprc;
	BOOLEAN_t	 canBusActive;
	BOOLEAN_t	 bonnetStatus;
	BOOLEAN_t	 lockStatus;
	BOOLEAN_t	 gsmStatus;
	long	*wheelTyreMotrSt	/* OPTIONAL */;
	long	 vehicleAlarmSt;
	long	 currentJourneyID;
	long	 journeyOdom;
	long	*frtLeftSeatHeatLel	/* OPTIONAL */;
	long	*frtRightSeatHeatLel	/* OPTIONAL */;
	BOOLEAN_t	*airCleanerSt	/* OPTIONAL */;
	BOOLEAN_t	 srsStatus;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RvsBasicStatus_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RvsBasicStatus;

#ifdef __cplusplus
}
#endif

#endif	/* _RvsBasicStatus_H_ */
#include <asn_internal.h>
