/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HOZON"
 * 	found in "HOZON_PRIV_v1.0.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_RvsVehicleInfo_H_
#define	_RvsVehicleInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct VSgpspos;

/* RvsVehicleInfo */
typedef struct RvsVehicleInfo {
	long	 infoTime;
	struct vigpsPos {
		A_SEQUENCE_OF(struct VSgpspos) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} vigpsPos;
	long	 infoSize;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RvsVehicleInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RvsVehicleInfo;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "VSgpspos.h"

#endif	/* _RvsVehicleInfo_H_ */
#include <asn_internal.h>
