/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HOZON"
 * 	found in "HOZON_PRIV_v1.0.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_VehicleSleepStInfo_H_
#define	_VehicleSleepStInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* VehicleSleepStInfo */
typedef struct VehicleSleepStInfo {
	long	 reason;
	long	*vehicleBatterySt	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VehicleSleepStInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleSleepStInfo;

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleSleepStInfo_H_ */
#include <asn_internal.h>
