/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HOZON"
 * 	found in "HOZON_PRIV_v1.0.asn"
 * 	`asn1c -gen-PER`
 */

#include "VehicleStAlertInfo.h"

static int
memb_vehicleStatus_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size == 1)) {
		/* Perform validation of the inner elements */
		return td->check_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_type_vehicleStatus_constr_2 GCC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  1,  1 }	/* (SIZE(1..1)) */,
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_vehicleStatus_constr_2 GCC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  1,  1 }	/* (SIZE(1..1)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_vehicleStatus_2[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RvsVehicleAlert,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_vehicleStatus_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_vehicleStatus_specs_2 = {
	sizeof(struct vehicleStatus),
	offsetof(struct vehicleStatus, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_vehicleStatus_2 = {
	"vehicleStatus",
	"vehicleStatus",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	SEQUENCE_OF_decode_uper,
	SEQUENCE_OF_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_vehicleStatus_tags_2,
	sizeof(asn_DEF_vehicleStatus_tags_2)
		/sizeof(asn_DEF_vehicleStatus_tags_2[0]) - 1, /* 1 */
	asn_DEF_vehicleStatus_tags_2,	/* Same as above */
	sizeof(asn_DEF_vehicleStatus_tags_2)
		/sizeof(asn_DEF_vehicleStatus_tags_2[0]), /* 2 */
	&asn_PER_type_vehicleStatus_constr_2,
	asn_MBR_vehicleStatus_2,
	1,	/* Single element */
	&asn_SPC_vehicleStatus_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_VehicleStAlertInfo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct VehicleStAlertInfo, vehicleStatus),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_vehicleStatus_2,
		memb_vehicleStatus_constraint_1,
		&asn_PER_memb_vehicleStatus_constr_2,
		0,
		"vehicleStatus"
		},
};
static const ber_tlv_tag_t asn_DEF_VehicleStAlertInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_VehicleStAlertInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* vehicleStatus */
};
static asn_SEQUENCE_specifics_t asn_SPC_VehicleStAlertInfo_specs_1 = {
	sizeof(struct VehicleStAlertInfo),
	offsetof(struct VehicleStAlertInfo, _asn_ctx),
	asn_MAP_VehicleStAlertInfo_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_VehicleStAlertInfo = {
	"VehicleStAlertInfo",
	"VehicleStAlertInfo",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_VehicleStAlertInfo_tags_1,
	sizeof(asn_DEF_VehicleStAlertInfo_tags_1)
		/sizeof(asn_DEF_VehicleStAlertInfo_tags_1[0]), /* 1 */
	asn_DEF_VehicleStAlertInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_VehicleStAlertInfo_tags_1)
		/sizeof(asn_DEF_VehicleStAlertInfo_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_VehicleStAlertInfo_1,
	1,	/* Elements count */
	&asn_SPC_VehicleStAlertInfo_specs_1	/* Additional specs */
};

