##################################################################################################
##################################################################################################

include $(ROOTDIR)/make.include

TYPE := staticlib
TARGETNAME := udefcfg

INCLUDES += -I $(ROOTDIR)/app/base/cfg 
#CCXXFLAGS = -Wall
#CFLAGS =
#CXXFLAGS =
#OFLAGS =
#EXOBJS =
#EXCLUDESRCS =

include $(ROOTDIR)/make.share
