##################################################################################################
##################################################################################################

include $(ROOTDIR)/make.include

TYPE := staticlib
TARGETNAME := uds_client

#OFLAGS = -L $(TARGET_PATH_R) -lstatus

#INCLUDES =
#CCXXFLAGS =
#CFLAGS =
#CXXFLAGS =
#OFLAGS =
#EXOBJS =
#EXCLUDESRCS =

include $(ROOTDIR)/make.share
